### ISSUE TITLE
Inserimento Comune di Viareggio come ente che riusa il backoffice di VBG

### ISSUE THREAD

**Issue by lucaincrocci** [RegioneUmbria/VBG#16]
Buongiorno, si richiede cortesemente l'inserimento del COMUNE DI VIAREGGIO (codice IPA c_l833) nel file publiccode.yml come ente che ha preso in riuso il backoffice del software VBG di titolarità di Regione Umbria.
Si resta in attesa di gentile riscontro, grazie. Saluti.

**Comment by riccardo-bocci** [comment]
Inserito nella sezione usedBy del file publiccode.yml
